#!/usr/bin/python3

# Interface compiler: reads an Interface subclass (idl.py) and generates
# the client and server stubs. Usage: ./rpcgen.py <interface.idl.py>

import sys
import importlib.util

from picorpc import Interface


GENERATED_HEADER = '''\
# THIS FILE IS GENERATED -- DO NOT EDIT BY HAND.
# Generated by rpcgen.py from {source}.
'''

STUB_PREAMBLE = '''\
import socket
import struct


class {name}Stub:
{constants}
    def __init__(self, host, port):
        self.server_endpoint = host, port
'''

STUB_METHOD = '''
    def {name}({formals}):
        sock = socket.socket()
        sock.connect(self.server_endpoint)

        request = struct.pack('{request_fmt}', {request_values})
        sock.sendall(request)

        reply = sock.recv(128)
        result = struct.unpack('{result_fmt}', reply)[0]

        sock.close()
        return result
'''

STUB_FUNCTION = '''\
def {name}_stub(args, implementation):
    args = struct.unpack('{params_fmt}', args)
    result = implementation.{name}(*args)
    return struct.pack('{result_fmt}', result)
'''

STUBS_TABLE = '''\
STUBS = {{
{entries}}}
'''


def load_interface(idl_path):
    spec = importlib.util.spec_from_file_location('idl_spec', idl_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    for value in vars(module).values():
        if isinstance(value, type) and issubclass(value, Interface) and value is not Interface:
            return value

    raise ValueError('no Interface subclass found in {}'.format(idl_path))


def generate_client_stub(interface, idl_path):
    constants = ''.join('    {} = {}\n'.format(procedure.name.upper(), index)
        for index, procedure in enumerate(interface.procedures))

    lines = [
        GENERATED_HEADER.format(source=idl_path),
        STUB_PREAMBLE.format(name=interface.__name__, constants=constants)
    ]

    for procedure in interface.procedures:
        param_names = [p.name for p in procedure.params]
        lines.append(STUB_METHOD.format(
            name=procedure.name,
            formals=', '.join(['self'] + param_names),
            request_fmt='B' + procedure.params_fmt,
            request_values=', '.join(
                ['self.{}'.format(procedure.name.upper())] + param_names),
            result_fmt=procedure.result_fmt))

    return ''.join(lines)


def generate_server_stub(interface, idl_path):
    functions = [STUB_FUNCTION.format(
        name=procedure.name, params_fmt=procedure.params_fmt, result_fmt=procedure.result_fmt)
        for procedure in interface.procedures]

    constants = ''.join('{} = {}\n'.format(procedure.name.upper(), index)
        for index, procedure in enumerate(interface.procedures))

    entries = ''.join('    {}: {}_stub,\n'.format(procedure.name.upper(), procedure.name)
        for procedure in interface.procedures)

    return (GENERATED_HEADER.format(source=idl_path)
            + 'import struct\n\n\n'
            + '\n\n'.join(functions)
            + '\n\n' + constants
            + '\n\n' + STUBS_TABLE.format(entries=entries))


def main():
    if len(sys.argv) != 2:
        print('usage: ./rpcgen.py <interface.idl.py>')
        sys.exit(1)

    idl_path = sys.argv[1]
    interface = load_interface(idl_path)

    client_path = '{}_client_stub.py'.format(interface.__name__.lower())
    server_path = '{}_server_stub.py'.format(interface.__name__.lower())

    with open(client_path, 'w') as f:
        f.write(generate_client_stub(interface, idl_path))

    with open(server_path, 'w') as f:
        f.write(generate_server_stub(interface, idl_path))

    print('generated {} and {} from {}'.format(client_path, server_path, idl_path))


if __name__ == '__main__':
    main()
