#!/usr/bin/python3

# Interface compiler: reads an Interface subclass (idl.py) and generates
# the client and server stubs. Usage: ./rpcgen.py <interface.idl.py>

import sys
import importlib.util

from picorpc import Interface


GENERATED_HEADER = '''\
# THIS FILE IS GENERATED -- DO NOT EDIT BY HAND.
# Generated by rpcgen.py from {source}.
'''


def load_interface(idl_path):
    spec = importlib.util.spec_from_file_location('idl_spec', idl_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    for value in vars(module).values():
        if isinstance(value, type) and issubclass(value, Interface) and value is not Interface:
            return value

    raise ValueError('no Interface subclass found in {}'.format(idl_path))


def generate_client_stub(interface, idl_path):
    lines = [GENERATED_HEADER.format(source=idl_path)]
    lines.append('import socket\n')
    lines.append('import struct\n\n\n')

    lines.append('class {}Stub:\n'.format(interface.__name__))
    for index, procedure in enumerate(interface.procedures):
        lines.append('    {} = {}\n'.format(procedure.name.upper(), index))
    lines.append('\n')

    lines.append('    def __init__(self, host, port):\n')
    lines.append('        self.server_endpoint = host, port\n')

    for procedure in interface.procedures:
        param_names = [p.name for p in procedure.params]
        formals = ', '.join(['self'] + param_names)
        request_fmt = 'B' + procedure.params_fmt
        request_values = ', '.join(
            ['self.{}'.format(procedure.name.upper())] + param_names)

        lines.append('\n')
        lines.append('    def {}({}):\n'.format(procedure.name, formals))
        lines.append('        sock = socket.socket()\n')
        lines.append('        sock.connect(self.server_endpoint)\n\n')
        lines.append("        request = struct.pack('{}', {})\n".format(
            request_fmt, request_values))
        lines.append('        sock.sendall(request)\n\n')
        lines.append('        reply = sock.recv(128)\n')
        lines.append("        result = struct.unpack('{}', reply)[0]\n\n".format(
            procedure.result_fmt))
        lines.append('        sock.close()\n')
        lines.append('        return result\n')

    return ''.join(lines)


def generate_server_stub(interface, idl_path):
    lines = [GENERATED_HEADER.format(source=idl_path)]
    lines.append('import struct\n\n\n')

    for index, procedure in enumerate(interface.procedures):
        if index > 0:
            lines.append('\n\n')
        lines.append('def {}_stub(args, implementation):\n'.format(procedure.name))
        lines.append("    params = struct.unpack('{}', args)\n".format(
            procedure.params_fmt))
        lines.append('    result = implementation.{}(*params)\n'.format(
            procedure.name))
        lines.append("    return struct.pack('{}', result)\n".format(
            procedure.result_fmt))

    lines.append('\n\n')
    for index, procedure in enumerate(interface.procedures):
        lines.append('{} = {}\n'.format(procedure.name.upper(), index))
    lines.append('\n\n')
    lines.append('STUBS = {\n')
    for procedure in interface.procedures:
        lines.append('    {}: {}_stub,\n'.format(
            procedure.name.upper(), procedure.name))
    lines.append('}\n')

    return ''.join(lines)


def main():
    if len(sys.argv) != 2:
        print('usage: ./rpcgen.py <interface.idl.py>')
        sys.exit(1)

    idl_path = sys.argv[1]
    interface = load_interface(idl_path)

    client_path = '{}_client_stub.py'.format(interface.__name__.lower())
    server_path = '{}_server_stub.py'.format(interface.__name__.lower())

    with open(client_path, 'w') as f:
        f.write(generate_client_stub(interface, idl_path))

    with open(server_path, 'w') as f:
        f.write(generate_server_stub(interface, idl_path))

    print('generated {} and {} from {}'.format(client_path, server_path, idl_path))


if __name__ == '__main__':
    main()
