#!/usr/bin/python3

# Interface compiler: reads an Interface subclass (idl.py) and generates
# the client proxy and the server stub. Usage: ./rmigen.py <interface.idl.py>

import sys
import importlib.util

from picormi import Interface, IDENTITY_SIZE


GENERATED_HEADER = '''\
# THIS FILE IS GENERATED -- DO NOT EDIT BY HAND.
# Generated by rmigen.py from {source}.
'''

PROXY_PREAMBLE = '''\
import socket
import struct

from picormi import encode_identity


class {name}Proxy:
{constants}
    def __init__(self, identity, host, port):
        self.identity = encode_identity(identity)
        self.server_endpoint = host, port
'''

PROXY_METHOD = '''
    def {name}({formals}):
        sock = socket.socket()
        sock.connect(self.server_endpoint)

        request = struct.pack('{request_fmt}', {request_values})
        sock.sendall(request)

        reply = sock.recv(128)
        result = struct.unpack('{result_fmt}', reply)[0]

        sock.close()
        return result
'''

SERVANT_PREAMBLE = '''\
import struct

from picormi import Servant


class {name}(Servant):
{constants}'''

SERVANT_METHOD = '''
    def {name}_stub(self, args):
        args = struct.unpack('{params_fmt}', args)
        result = self.{name}(*args)
        return struct.pack('{result_fmt}', result)
'''

STUBS_TABLE = '''
    STUBS = {{
{entries}    }}
'''


def load_interface(idl_path):
    spec = importlib.util.spec_from_file_location('idl_spec', idl_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    for value in vars(module).values():
        if isinstance(value, type) and issubclass(value, Interface) and value is not Interface:
            return value

    raise ValueError('no Interface subclass found in {}'.format(idl_path))


def _constants(methods):
    return ''.join('    {} = {}\n'.format(method.name.upper(), index)
        for index, method in enumerate(methods))


def generate_proxy(interface, idl_path):
    lines = [
        GENERATED_HEADER.format(source=idl_path),
        PROXY_PREAMBLE.format(
            name=interface.__name__, constants=_constants(interface.methods))
    ]

    for method in interface.methods:
        param_names = [p.name for p in method.params]
        lines.append(PROXY_METHOD.format(
            name=method.name,
            formals=', '.join(['self'] + param_names),
            request_fmt='{}sB{}'.format(IDENTITY_SIZE, method.params_fmt),
            request_values=', '.join(
                ['self.identity', 'self.{}'.format(method.name.upper())] + param_names),
            result_fmt=method.result_fmt))

    return ''.join(lines)


def generate_server_stub(interface, idl_path):
    lines = [
        GENERATED_HEADER.format(source=idl_path),
        SERVANT_PREAMBLE.format(
            name=interface.__name__,
            constants=_constants(interface.methods))]

    for method in interface.methods:
        lines.append(SERVANT_METHOD.format(
            name=method.name, params_fmt=method.params_fmt, result_fmt=method.result_fmt))

    entries = ''.join('        {}: {}_stub,\n'.format(method.name.upper(), method.name)
                       for method in interface.methods)
    lines.append(STUBS_TABLE.format(entries=entries))

    return ''.join(lines)


def main():
    if len(sys.argv) != 2:
        print('usage: ./rmigen.py <interface.idl.py>')
        sys.exit(1)

    idl_path = sys.argv[1]
    interface = load_interface(idl_path)

    client_path = '{}_client_stub.py'.format(interface.__name__.lower())
    server_path = '{}_server_stub.py'.format(interface.__name__.lower())

    with open(client_path, 'w') as f:
        f.write(generate_proxy(interface, idl_path))

    with open(server_path, 'w') as f:
        f.write(generate_server_stub(interface, idl_path))

    print('generated {} and {} from {}'.format(client_path, server_path, idl_path))


if __name__ == '__main__':
    main()
